[package]
name = "raw-renderer"
version = "0.1.0"
authors = ["mandeep <mandeep@users.noreply.github.com>"]

[dependencies]
image = "0.18.0"
wavefront_obj = "5.1.0"


[profile.dev]
opt-level = 2
debug = true
incremental = true
