[package]
name = "morpheus"
version = "0.1.0"
authors = ["mandeep <mandeep@users.noreply.github.com>"]

[dependencies]
image = "0.18.0"
nalgebra = "0.14.1"

[profile.dev]
opt-level = 2
debug = true
incremental = true
